### ISSUE TITLE
webpack 打包之后的文件在哪儿？

### ISSUE THREAD

**Issue by MrKou47** [L-movingon/isomorphic-react-workflow-boilerplate#2]

**Comment by jasonliao** [comment]
你好，打包生成的文件路径为 `/public/static/` 下。但是在 dev 模式下，webpack 生成的 `bundle.js` 不会真正生成出来，会存在内存里，这样就可以更快的 diff，实现 Hot Module Replacement。更详细可以看 [这里](https://webpack.github.io/docs/webpack-dev-server.html)
